function [ s ] = score( message )
%用频率计算得分，不完整
    s = count(message,'al')*15+count(message,'an')*44+count(message,'ar')*14+count(message,'as')*12+count(message,'at')*20+count(message,'av')*5+count(message,'ay')*5+...
    count(message,'be')*12+count(message,'bl')*2+count(message,'bo')*2+count(message,'br')*2+count(message,'bu')*2+count(message,'by')*2+...
    count(message,'ca')*6+count(message,'ce')*6+count(message,'ch')*8+count(message,'co')*8+...
    count(message,'de')*8+count(message,'di')*5+count(message,'do')*3+count(message,'dr')+count(message,'ds')*2+count(message,'du')+...
    count(message,'ea')*12+count(message,'ed')*15+count(message,'ee')*7+count(message,'ei')*4+count(message,'el')*8+count(message,'em')*6+count(message,'en')*20+count(message,'er')*20+count(message,'es')*16+count(message,'et')*8+count(message,'ev')*4+count(message,'ex')+count(message,'ey')*4+...
    count(message,'fa')*2+count(message,'fe')+count(message,'fo')*8+count(message,'fr')*3+...
    count(message,'ga')+count(message,'ge')*4+count(message,'go')*4+count(message,'gr')*2+...
    count(message,'ha')*24+count(message,'he')*71+count(message,'hi')*18+count(message,'ho')*10+count(message,'hy')*2+...
    count(message,'ic')*5+count(message,'id')*5+count(message,'ie')*5+count(message,'il')*7+count(message,'im')*6+count(message,'in')*33+count(message,'io')*5+count(message,'ir')*5+count(message,'is')*16+count(message,'it')*16+count(message,'iv')*3+...
    count(message,'ja')+count(message,'je')+count(message,'jo')+count(message,'ju')+count(message,'ja')+...
    count(message,'ke')*5+count(message,'ki')*2+count(message,'kn')+...
    count(message,'la')*6+count(message,'ld')*5+count(message,'le')*11+count(message,'li')*5+count(message,'ll')*14+count(message,'lo')*8+count(message,'ly')*4+...
    count(message,'ma')*8+count(message,'mb')+count(message,'me')*12+count(message,'mm')+count(message,'mo')*5+count(message,'mp')+count(message,'ms')+count(message,'mu')+count(message,'my')*2+...
    count(message,'nc')*4+count(message,'nd')*35+count(message,'ne')*10+count(message,'ng')*14+count(message,'ns')*5+count(message,'nt')*13+count(message,'ny')+...
    count(message,'oa')+count(message,'ob')+count(message,'oc')+count(message,'od')*4+count(message,'of')*21+count(message,'ok')+count(message,'ol')+count(message,'om')*8+count(message,'on')*19+count(message,'oo')*3+count(message,'op')*2+count(message,'or')*20+count(message,'os')*3+count(message,'ot')*7+count(message,'ou')*19+count(message,'ov')*2+count(message,'ow')*6+...
    count(message,'pa')*3+count(message,'pe')*5+count(message,'ph')+count(message,'pi')+count(message,'pl')*3+count(message,'po')*3+count(message,'pp')+count(message,'pr')*4+count(message,'pt')+count(message,'pu')+...
    count(message,'qu')+...
    count(message,'ra')*7+count(message,'re')*75+count(message,'ri')*8+count(message,'rk')+count(message,'rm')+count(message,'rn')*2+count(message,'ro')*8+count(message,'rr')+count(message,'rs')*4+count(message,'rt')*4+count(message,'ru')*2+count(message,'rv')+count(message,'ry')*2+...
    count(message,'sa')*7+count(message,'sc')+count(message,'se')*15+count(message,'sh')*8+count(message,'si')*4+count(message,'so')*6+count(message,'sp')*3+count(message,'sr')+count(message,'ss')*4+count(message,'st')*13+count(message,'su')*2+...
    count(message,'ta')*5+count(message,'te')*11+count(message,'th')*85+count(message,'ti')*8+count(message,'tl')+count(message,'to')*17+count(message,'tr')*4+count(message,'ts')*3+count(message,'tt')*2+count(message,'tu')*2+count(message,'tw')+count(message,'ty')*2+...
    count(message,'ua')+count(message,'ub')+count(message,'uc')+count(message,'ud')+count(message,'ue')+count(message,'ug')+count(message,'ui')+count(message,'ul')*4+count(message,'um')+count(message,'un')*8+count(message,'up')*3+count(message,'ur')*7+count(message,'us')*7+count(message,'ut')*7+...
    count(message,'va')+count(message,'ve')*14+count(message,'vi')*2+...
    count(message,'wa')*7+count(message,'we')*7+count(message,'wh')*8+count(message,'wi')*8+count(message,'wn')+count(message,'wo')*3+...
    count(message,'ye')*3+count(message,'yo')*3+count(message,'ys');
end

